// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSAP0GJ6P-x4bTOTNmHTDH6cmU54616HU',
    appId: '1:971902571526:web:611eb4c4e0d6b3049c1f87',
    messagingSenderId: '971902571526',
    projectId: 'gallery-8bb0d',
    authDomain: 'gallery-8bb0d.firebaseapp.com',
    storageBucket: 'gallery-8bb0d.firebasestorage.app',
    measurementId: 'G-RP1TLF6C0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAhN1ytNvyoDwfTZQ-SUdTaVVbWhNWfQM',
    appId: '1:971902571526:android:a7a35e997aef92a09c1f87',
    messagingSenderId: '971902571526',
    projectId: 'gallery-8bb0d',
    storageBucket: 'gallery-8bb0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn2_O-IqvkR8XTRPU8lxKvwsMjPSdUCNk',
    appId: '1:971902571526:ios:f0e5d8a2b4d6b3639c1f87',
    messagingSenderId: '971902571526',
    projectId: 'gallery-8bb0d',
    storageBucket: 'gallery-8bb0d.firebasestorage.app',
    iosBundleId: 'com.example.pixvault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn2_O-IqvkR8XTRPU8lxKvwsMjPSdUCNk',
    appId: '1:971902571526:ios:f0e5d8a2b4d6b3639c1f87',
    messagingSenderId: '971902571526',
    projectId: 'gallery-8bb0d',
    storageBucket: 'gallery-8bb0d.firebasestorage.app',
    iosBundleId: 'com.example.pixvault',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSAP0GJ6P-x4bTOTNmHTDH6cmU54616HU',
    appId: '1:971902571526:web:5a596968b246ea209c1f87',
    messagingSenderId: '971902571526',
    projectId: 'gallery-8bb0d',
    authDomain: 'gallery-8bb0d.firebaseapp.com',
    storageBucket: 'gallery-8bb0d.firebasestorage.app',
    measurementId: 'G-XZ6Y3YH4L5',
  );
}
